image: docker:latest

variables:
  REGISTRY_HOST: harbor.XXXXXXX.com
  PROJECT_NAME: darreng
  TEST_IMAGE: $REGISTRY_HOST/$PROJECT_NAME/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  RELEASE_IMAGE: $REGISTRY_HOST/$PROJECT_NAME/$CI_PROJECT_PATH:latest
  DEPLOYMENT_URL: XXXXXXXXX
  RANCHER_TOKEN: token-6sqgw:rtnv4nj68hvfkkxllzwxgf85hmlchsjhm64phz7n5ct2dlpcrj49q4

stages:
  - build
  - release
  - deploy

build:
  stage: build
  script:
    - docker info
    - docker login -u admin -p Harbor12345 $REGISTRY_HOST
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
  only:
    - master

release:
  stage: release
  script:
    - docker info
    - docker login -u admin -p Harbor12345 $REGISTRY_HOST
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: python:3.7.1-alpine3.7
  script:
    - pip install requests
    - python3 rancher-deploy.py $DEPLOYMENT_URL $RANCHER_TOKEN
  only:
    - master
